DROP TABLE customer     CASCADE CONSTRAINTS;
DROP TABLE employee 	CASCADE CONSTRAINTS;
DROP TABLE supplier   	CASCADE CONSTRAINTS;
DROP TABLE invoice     	CASCADE CONSTRAINTS;
DROP TABLE sold_items 	CASCADE CONSTRAINTS;
DROP TABLE item  		CASCADE CONSTRAINTS;
DROP TABLE category     CASCADE CONSTRAINTS;
DROP TABLE shipments    CASCADE CONSTRAINTS;

COMMIT;